import type { Metadata } from "next";
//import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const items = [
  {key: "tasks", label: <a href={"/tasks"}>Задачи</a>},
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        
      </body>
    </html>
  );
}
